apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: argo-cd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.0.10
    valuesFile: values.yaml
    namespace: argocd

helmGlobals:
  chartHome: charts
  configHome: config
